CREATE TABLE EnderecosFuncionarios (
   IdEnderecoFuncionario INTEGER IDENTITY(01, 01),
   IdFuncionario SMALLINT NOT NULL,
   IdVia INTEGER NOT NULL,
   IdTipoEndereco TINYINT NOT NULL,
   IdLoteamento SMALLINT NULL,
   IdLote SMALLINT NULL,
   IdQuadra SMALLINT NULL,
   IdCondominio SMALLINT NULL,
   IdDistrito SMALLINT NULL,
   Numero INTEGER NULL,
   Complemento VARCHAR(25) NULL,
CONSTRAINT PK_EnderecosFuncionarios PRIMARY KEY(IdEnderecoFuncionario),
CONSTRAINT FK_EnderecosFuncionarios_Vias FOREIGN KEY(IdVia) REFERENCES Vias(IdVia),
CONSTRAINT FK_EnderecosFuncionarios_Funcionarios FOREIGN KEY(IdFuncionario) REFERENCES Funcionarios(IdFuncionario),
CONSTRAINT FK_EnderecosFuncionarios_TiposEndereco FOREIGN KEY(IdTipoEndereco) REFERENCES TiposEndereco(IdTipoEndereco),
CONSTRAINT FK_EnderecosFuncionarios_Loteamento FOREIGN KEY(IdLoteamento) REFERENCES Loteamentos(IdLoteamento),
CONSTRAINT FK_EnderecosFuncionarios_Lote FOREIGN KEY(IdLote) REFERENCES Lotes(IdLote),
CONSTRAINT FK_EnderecosFuncionarios_Quadra FOREIGN KEY(IdQuadra) REFERENCES Quadras(IdQuadra),
CONSTRAINT FK_EnderecosFuncionarios_Condominio FOREIGN KEY(IdCondominio) REFERENCES Condominios(IdCondominio),
CONSTRAINT FK_EnderecosFuncionarios_Distrito FOREIGN KEY(IdDistrito) REFERENCES Distritos(IdDistrito))